### ISSUE TITLE
[Bug]: Key mapping not working while using keyboard on MacOS 14

### ISSUE THREAD

**Issue by Oblivious27** [PlayCover/PlayCover#1048]
### Describe the bug

Bug : Command + K to call the key mapping is fine, but any key input from keyboard fails , while the left and right click of mouse is ok to key map.
Others: While input keys for key mapping ,I heard the system sound of key input. This sound is often heard when the key is not inputting in the active window.
Device : Macbook air M2 16GB ,
System: Mac OS 14.0 Sonoma Developer beta
version of PlayCover : Nightly/Beta, 3.0

<img width="113" alt="image" src="https://github.com/PlayCover/PlayCover/assets/140101613/9569a02b-297b-4b0c-94ae-b372a9d3a38d">

### Steps to reproduce

Command + K and press any Key from Keyboard.
The system sound of the key shows it is not inputting in the active window

### Expected behaviour

Key mapping as normal use

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               hkrpg [16222]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/hkrpg.app/hkrpg
Identifier:            com.miHoYo.hkrpg
Version:               1.2.0 (3)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-21 11:30:11.5763 +0800
OS Version:            macOS 14.0 (23A5286i)
Report Version:        12
Anonymous UUID:        F78B1EBC-5517-3FD8-F01C-4D9C0FEC4BCD

Sleep/Wake UUID:       9736168F-6DC2-41AA-8068-4FD78A09FFE8

Time Awake Since Boot: 10000 seconds
Time Since Wake:       8278 seconds

System Integrity Protection: enabled

Crashed Thread:        60  Dispatch queue: com.Metal.CompletionQueueDispatch

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000393169d49160
Exception Codes:       0x0000000000000001, 0x0000393169d49160

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [16222]

VM Region Info: 0x393169d49160 is not in any region.  Bytes after previous region: 62403355382113  Bytes before following region: 42668724547232
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Sonoma (macOS 14 beta)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Moxuan6** [comment]
me too!

**Comment by seti02** [comment]
me too!  I'm very irritable, and I hope it can be solved!

**Comment by fgwyi** [comment]
me too!Playcover2.0.5 will also do so.

**Comment by xiaokang00010** [comment]
I met the same problem on macOS 14 Sonoma Beta 3 with PlayCover version 3.0.0 build 427.

**Comment by yaoWaaa** [comment]
Me too ! plz fix it!

**Comment by AkshayanSingla** [comment]
Not getting fixed until official release of macOS Sonoma.

**Comment by master-lzh** [comment]
The same problem in macOS 14 Sonoma beta，I can't play Genshin Impact and Star Rail on it.

**Comment by Dariozuo** [comment]
me too

**Comment by immoutal** [comment]
For the time being my workaround is to get keymaps from https://github.com/PlayCover/keymaps. You can also export your own keymaps (right click on game icon in PlayCover, "Import/Export keymapping") and tweak them as needed in a text editor - it's just XML.

**Comment by jingyenoting** [comment]
> XML.

The problem is the keyboard don't give me any response in the playcover

**Comment by jingyenoting** [comment]
> For the time being my workaround is to get keymaps from https://github.com/PlayCover/keymaps. You can also export your own keymaps (right click on game icon in PlayCover, "Import/Export keymapping") and tweak them as needed in a text editor - it's just XML.

The problem is the keyboard don't give me any response in the playcover

**Comment by jingyenoting** [comment]
> > The problem is the keyboard don't give me any response in the playcover
> 
> Press option key on your keyboard; Keymapping is toggled using the option key. If it still doesn’t work, please wait for macOS Sonoma’s official release.

OK,thank you

**Comment by imoutal** [comment]
In my case keymapping editor stopped accepting keyboard after upgrading to Sonoma beta too, but all keys still work just fine when using an imported keymap.

**Comment by jingyenoting** [comment]
> In my case keymapping editor stopped accepting keyboard after upgrading to Sonoma beta too, but all keys still work just fine when using an imported keymap.

You mean that you use the other people's keymap that can be work in Sonoma14.0?

**Comment by imoutal** [comment]
> You mean that you use the other people's keymap that can be work in Sonoma14.0?
Yeah, I play Genshin on Sonoma 14.0 using a keymap from the repo I linked earlier.

**Comment by Kkevinnnnnn** [comment]
I meat the problem as well when I just updated my mac into MacOS 14.0 Sonoma. The keymap can't work properly although it is successfully input. I keep trying typing Option key but it doesn't change into keyboard mode and cmd+k can only be used for once to open the editing page but if I type cmd+k again, the page cannot be closed. I have tried to restart my Mac and reput the keymap, however, it doesn't work at all. Fix it soon pls!!! I even want to downdate my MacOS cause I cannot play Genshin any longer.

**Comment by Kkevinnnnnn** [comment]
> I meat the problem as well when I just updated my mac into MacOS 14.0 Sonoma. The keymap can't work properly although it is successfully input. I keep trying typing Option key but it doesn't change into keyboard mode and cmd+k can only be used for once to open the editing page but if I type cmd+k again, the page cannot be closed. I have tried to restart my Mac and reput the keymap, however, it doesn't work at all. Fix it soon pls!!! I even want to downdate my MacOS cause I cannot play Genshin any longer.

OK. Cool! The problem is fixed after I update the playcover into 3.0.0.

**Comment by jingyenoting** [comment]
> > I meat the problem as well when I just updated my mac into MacOS 14.0 Sonoma. The keymap can't work properly although it is successfully input. I keep trying typing Option key but it doesn't change into keyboard mode and cmd+k can only be used for once to open the editing page but if I type cmd+k again, the page cannot be closed. I have tried to restart my Mac and reput the keymap, however, it doesn't work at all. Fix it soon pls!!! I even want to downdate my MacOS cause I cannot play Genshin any longer.
> 
> 
> 
> OK. Cool! The problem is fixed after I update the playcover into 3.0.0.

Iwas the same with you but As I update it into 3.0.0 the keyboard still didn't work at all

**Comment by Kkevinnnnnn** [comment]
> > > I meat the problem as well when I just updated my mac into MacOS 14.0 Sonoma. The keymap can't work properly although it is successfully input. I keep trying typing Option key but it doesn't change into keyboard mode and cmd+k can only be used for once to open the editing page but if I type cmd+k again, the page cannot be closed. I have tried to restart my Mac and reput the keymap, however, it doesn't work at all. Fix it soon pls!!! I even want to downdate my MacOS cause I cannot play Genshin any longer.
> > 
> > 
> > OK. Cool! The problem is fixed after I update the playcover into 3.0.0.
> 
> Iwas the same with you but As I update it into 3.0.0 the keyboard still didn't work at all

Though I can change between keyboard and mouse, editing the keys stiil doesn't work. It always shows the LMB. The bugs are so much so I think we can only wait the official version to be released.

**Comment by TheMoonThatRises** [comment]
Should be fixed with PR https://github.com/PlayCover/PlayTools/pull/120 by @XuYicong.

**Comment by master-lzh** [comment]
> 应通过 PR PlayCover [/PlayTools#120修复](https://github.com/PlayCover/PlayTools/pull/120)@XuYicong。

I tried it and the editing function is normal, but pressing the option key still cannot make the keyboard mapping layout take effect.

**Comment by jingyenoting** [comment]
> > 应通过 PR PlayCover [/PlayTools#120修复](https://github.com/PlayCover/PlayTools/pull/120)@XuYicong。
> 
> 
> 
> I tried it and the editing function is normal, but pressing the option key still cannot make the keyboard mapping layout take effect.

Me too

**Comment by XuYicong** [comment]
> > 应通过 PR PlayCover [/PlayTools#120修复](https://github.com/PlayCover/PlayTools/pull/120)@XuYicong。
> 
> I tried it and the editing function is normal, but pressing the option key still cannot make the keyboard mapping layout take effect.

That's out of the scope of this issue. You should open another issue and describe it in details.

**Comment by jingyenoting** [comment]
Has it been finished?

**Comment by TheMoonThatRises** [comment]
The PR is merged and is in the most recently nightly build.

**Comment by jingyenoting** [comment]
Ok thank you

**Comment by jingyenoting** [comment]
Is it OK now for the Sonoma 14.0 official version?

**Comment by pipe119** [comment]
I think is a Sonoma bug, I'm using the Sonoma official release on my MacBook Air M1 and my keyboard don't work on PlayCover but the same issue happen in iPad/iOS apps under controller emulation. I tried to play GTA:SA using the controller emulation but nothing happens and sometimes game crashes if the emulation option is on.

**Comment by realrazing929** [comment]
I play Stumble Guys through PlayCover, however I have to use left click to jump which is super confusing because I'm so used to jumping with Space but I can't do that because when I try editing a key mappings and try switching it to Space, it doesn't work. Hope this can be resolve asap
My Computer: Mac Mini M1 Chip, 8 GB RAM
