### ISSUE TITLE
[Bug]: Discord Rich Presence does not work

### ISSUE THREAD

**Issue by MEMORIEmusic** [PlayCover/PlayCover#1112]
### Describe the bug

Discord Rich Presence feature of PlayCover does not work on macOS Sonoma 14.0
Furthermore, Custom Discord Activity has stopped working as well. 
 

### Steps to reproduce

1. Launch a game 
2. Open Discord 
3. No Activity/rich presence 

### Expected behaviour

Opened game should show up as an activity on the user’s Discord profile. 

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

macOS beta (please state the specific version)

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
1. Do you have the Discord app?
2. Did you open Discord before launching the game?

The Discord rich presence only works if the Discord app is open before launching the game due to how the rich presence feature works.

**Comment by MEMORIEmusic** [comment]
> 1. Do you have the Discord app?
> 2. Did you open Discord before launching the game?
> 
> The Discord rich presence only works if the Discord app is open before launching the game due to how the rich presence feature works.

Positive for both.

**Comment by MEMORIEmusic** [comment]
<img width="694" alt="Screenshot 2023-10-01 at 10 23 40" src="https://github.com/PlayCover/PlayCover/assets/79436281/ff9305ba-e7f0-4781-83fd-293b48f1966a">

<img width="1061" alt="Screenshot 2023-10-01 at 10 24 29" src="https://github.com/PlayCover/PlayCover/assets/79436281/549de183-5bc9-4778-bab6-27b83056035c">

<img width="1800" alt="Screenshot 2023-10-01 at 10 33 29" src="https://github.com/PlayCover/PlayCover/assets/79436281/e9f06ec9-2751-44ab-809f-b91c8ed9243e">

**Comment by zanderp25** [comment]
I'm able to replicate this issue in the 3.0.0 beta

**Comment by ghost** [comment]
Replicated issue in 3.0.0 Nightly (514). While I can't test every app, it seems to affect most of them.

**Comment by TheMoonThatRises** [comment]
This might have been fixed on the latest version of Sonoma Beta. If someone is on it, can you check it please?

**Comment by ghost** [comment]
> This might have been fixed on the latest version of Sonoma Beta. If someone is on it, can you check it please?

macOS 14.1 RC seems to be out now. Not sure if it fixes it, but I may check later if I end up installing the RC. If not we'll know in a week, I guess.

**Comment by ghost** [comment]
@TheMoonThatRises I just tested PlayCover (Nightly 522) on macOS Sonoma 14.1's stable release. The Discord status still doesn't work.

Additionally, there's some weird issue now causing all games to not even open on the new macOS release. It is referenced in #1108, but there hasn't been an official fix in place despite the issue being known for a month.
