### ISSUE TITLE
[Game Support]: Wuthering Waves: mouse randomly fails to pan then zooms in and out instead.

### ISSUE THREAD

**Issue by bbajr** [PlayCover/PlayCover#1483]
### App Store link

https://apps.apple.com/us/app/wuthering-waves/id6475033368

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

After playing WuWa for a few minutes, the mouse panning fails. I will have pressed option a few times and back to use cursors by then. I have attached my keymap below. 
[WutheringWavesKeymap.playmap.zip](https://github.com/PlayCover/PlayCover/files/15422312/WutheringWavesKeymap.playmap.zip)

Mouse zooms in and out instead of panning. Only restart has fixed my problem.
Playcover Nightly: Version 3.0.0 (751)

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kang49** [comment]
I confirm this issue is true.

**Comment by LeeeSe** [comment]
The temporary solution is to press M to open the map and return to normal after shaking the mouse.

**Comment by kang49** [comment]
> The temporary solution is to press M to open the map and return to normal after shaking the mouse.

Do you think this's PlayCover's issue or at the game? But i never seen this issue on iOS platform.

**Comment by Kxcnw** [comment]
> > The temporary solution is to press M to open the map and return to normal after shaking the mouse.
> 
> Do you think this's PlayCover's issue or at the game? But i never seen this issue on iOS platform.

probably playcover, i remember this happening to me a while back on genshin

**Comment by huafeng-yang** [comment]
> 临时解决办法是按M打开地图，摇晃鼠标后恢复正常。

感谢您分享的方法，但并非每次都能生效，有时还需要重启才可以解决问题

**Comment by hpycndl** [comment]
> The temporary solution is to press M to open the map and return to normal after shaking the mouse.

Thank you for sharing this. 
I don't know if today's update did something. 
But I have been playing for 2 hours without camera getting zoom-locked.

**Comment by kang49** [comment]
I found a temporary solution. Just press "CMD+R" to rotate screen and it's work.

**Comment by ngocsok** [comment]
> I found a temporary solution. Just press "CMD+R" to rotate screen and it's work.

Same problem here.  I know where the problem lies:
 1. The problem occurs because the user sets the attack key as the left mouse button. During combat, the player will continuously press the left mouse button to attack.  Meanwhile, moving the screen means the left mouse button is always held in the middle of the screen, this causes the same left mouse button to have 2 active functions, this conflict causes Playcover to fail and it will  Overwriting one more time means it will be like swiping two fingers on the touch screen, which causes the screen to zoom in and out without moving the camera.
 2. You just need to set the attack key to another button, for example, attack will usually be the E button and never left click the mouse without releasing the mouse.  This will make it harder for errors to appear.
 3. As for developer WuWa, it looks like they are going to support mouse and keyboard for mobile devices so you can see that even if you don't map or install any buttons for the game,  still there but keyboard operation can be used.  For example, buttons 1,2,3 switch characters, T button to launch an air hook, M button to open the map... And similarly with the Option or Alt button used to release the mouse, but the problem is  Both Playcover and WuWa use this button, this makes it so that when you press it to release the mouse both Wuwa and Playcover will release the mouse at the same time, mostly Playcover will release but sometimes the game recognizes the mouse release key, immediately  This means you will not be able to move the mouse pointer anymore.
 Those are 2 issues that I think are happening at the same time causing the game to only work for a few minutes then the mouse won't work.
 I will try your method, hope it helps me temporarily.
 Hope there is a radical solution to this.

**Comment by kang49** [comment]
# Summary of the issue:

### Steps to reproduce the bug:
1. Assign the attack action to the Left Mouse Button (LMB).
2. Press and hold LMB to charge the attack.
3. Press and hold the Option key (while still holding LMB).
4. Release the LMB to stop charging the attack.
5. Press and hold the Option key again, and move the mouse to change the view while the pointer is visible.
6. Press the Option key to hide the pointer; the bug will occur immediately.

### Steps to fix the issue:
1. Press the Option key (you'll notice that even though the mouse button isn't pressed, the view still moves).
2. Click anywhere once.
3. Press the Option key again to hide the pointer, and everything should return to normal.

What I believe needs to be fixed in PlayCover is that when the Option key is pressed, all previously held keys should be reset. No command should remain active after pressing the Option key to show or hide the pointer.

### Video demonstration:
[https://youtu.be/6bSCDkJ41BU](https://youtu.be/6bSCDkJ41BU)

**Comment by XuYicong** [comment]
Since it has native mouse button support you don't have to map attack key right? Just remove mapping of left mouse button and issue should be resolved?

**Comment by kang49** [comment]
> Since it has native mouse button support you don't have to map attack key right? Just remove mapping of left mouse button and issue should be resolved?

Yes, i did it right now.

**Comment by bbajr** [comment]
> ### Steps to fix the issue:
> 1. Press the Option key (you'll notice that even though the mouse button isn't pressed, the view still moves).
> 2. Click anywhere once.
> 3. Press the Option key again to hide the pointer, and everything should return to normal.

This didn't fix mine. 
When I press the Option key, the view doesn't move if i don't press the moust button.

Also, I dunno if something changed; 
attack button without mapping works fine with touchpad but not with bluetooth mouse.

**Comment by kang49** [comment]
> > ### Steps to fix the issue:
> > 
> > 1. Press the Option key (you'll notice that even though the mouse button isn't pressed, the view still moves).
> > 2. Click anywhere once.
> > 3. Press the Option key again to hide the pointer, and everything should return to normal.
> 
> This didn't fix mine. When I press the Option key, the view doesn't move if i don't press the moust button.
> 
> Also, I dunno if something changed; attack button without mapping works fine with touchpad but not with bluetooth mouse.

Try removing the left mouse button (LMB) mapping first and wait for this issue to be resolved. You can re-map it later as suggested by [XuYicong](https://github.com/XuYicong).

**Comment by ngocsok** [comment]
When it was first launched, Wuwa integrated mouse operations with the right mouse button for surfing and the left mouse button for attack.  But in the latest update they removed the mouse action, which means you will be forced to assign attacks to the mouse, causing the camera movement error to appear more often.  Also I tried with Genshin, Wuwa and Punishing Gray Raven.  The error occurs with all 3 of these games.

**Comment by bbajr** [comment]
> Try removing the left mouse button (LMB) mapping first and wait for this issue to be resolved. You can re-map it later as suggested by [XuYicong](https://github.com/XuYicong).

I started playing with the middle mouse button mapped for attack. The issue occured again

**Comment by kang49** [comment]
> > Try removing the left mouse button (LMB) mapping first and wait for this issue to be resolved. You can re-map it later as suggested by [XuYicong](https://github.com/XuYicong).
> 
> I started playing with the middle mouse button mapped for attack. The issue occured again

Why you use MMB? I mean you remove all mapping that can atk and by default WutheringWaves already can atk by LMB.

**Comment by bbajr** [comment]
> Why you use MMB? I mean you remove all mapping that can atk and by default WutheringWaves already can atk by LMB.

By default my mouse cannot atk. I think they removed that functionality in recent patches.

**Comment by XuYicong** [comment]
When the issue happens, if you press CMD+K twice, would it fix it?

**Comment by XuYicong** [comment]
> This didn't fix mine. When I press the Option key, the view doesn't move if i don't press the moust button.
> 

Your issue is probably different from his. Can you provide a screen recording of it? Or describe what actions have you taken to trigger the issue. When you say "pan" is it like holding left mouse button and drag, or solely move without pressing anything? With cursor shown or hidden? I believe you don't drag screen and press option in normal play like he does right?

**Comment by bbajr** [comment]
> Your issue is probably different from his. Can you provide a screen recording of it? Or describe what actions have you taken to trigger the issue. When you say "pan" is it like holding left mouse button and drag, or solely move without pressing anything? With cursor shown or hidden? I believe you don't drag screen and press option in normal play like he does right?

Sorry. I was not very clear. I don't know how to trigger it. But it happens after minutes of playing.

I just meant the view doesn't move when i don't press any button with cursor shown (which I activated with option key).
I press option to go to cursor mode, click some stuff and press option again to go normal keymapped gaming mode.

**Comment by LeeeSe** [comment]
Why don‘t you open the map and shake the mouse at will, and everything will return to normal?

**Comment by bbajr** [comment]
> Why don‘t you open the map and shake the mouse at will, and everything will return to normal?


Can you send me a demo on how to do it?
Following is my attempt. It changed nothing.
I tried both shaking the map with/without my alt active. with/without holding my left mouse button.
[2024-05-25 22-24-02.mkv.zip](https://github.com/PlayCover/PlayCover/files/15445845/2024-05-25.22-24-02.mkv.zip)

**Comment by huafeng-yang** [comment]
> 一下

纯电脑小白，我看到您修复了这个问题，但是我不懂怎么把它应用在我的playcover上呢？

**Comment by akifolgun** [comment]
> > Geçici bir çözüm buldum. Ekranı döndürmek için "CMD+R" tuşlarına basmanız yeterlidir; işe yarar.
> 
> Burada da aynı problem. Sorunun nerede olduğunu biliyorum:
> 
> 1. Sorun, kullanıcının saldırı tuşunu farenin sol düğmesi olarak ayarlaması nedeniyle oluşur. Dövüş sırasında oyuncu saldırmak için sürekli olarak farenin sol tuşuna basacaktır. Bu arada ekranı hareket ettirmek, sol fare düğmesinin her zaman ekranın ortasında tutulması anlamına gelir, bu aynı sol fare düğmesinin 2 aktif fonksiyona sahip olmasına neden olur, bu çakışma Playcover'ın başarısız olmasına neden olur ve üzerine bir kez daha yazmak, bunun olacağı anlamına gelir. iki parmağınızı dokunmatik ekranda kaydırmak gibi, bu da kamerayı hareket ettirmeden ekranın yakınlaştırılmasına ve uzaklaştırılmasına neden olur.
> 2. Saldırı tuşunu başka bir düğmeye ayarlamanız yeterlidir; örneğin, saldırı genellikle E düğmesi olur ve fareyi bırakmadan asla fareye sol tıklamazsınız. Bu, hataların ortaya çıkmasını zorlaştıracaktır.
> 3. Geliştirici WuWa'ya gelince, mobil cihazlar için fare ve klavyeyi destekleyecek gibi görünüyor, böylece oyun için herhangi bir düğme eşleştirmeseniz veya yüklemeseniz bile hala orada olduğunu ancak klavye işleminin kullanılabileceğini görebilirsiniz. Örneğin, karakterleri değiştirecek 1,2,3 düğmeleri, hava kancasını başlatmak için T düğmesi, haritayı açmak için M düğmesi... Ve fareyi serbest bırakmak için kullanılan Option veya Alt düğmesiyle benzer şekilde, ancak sorun Hem Playcover hem de Playcover'dır. WuWa bu düğmeyi kullanır, bu öyle yapar ki fareyi bırakmak için ona bastığınızda hem Wuwa hem de Playcover fareyi aynı anda bırakır, çoğunlukla Playcover serbest kalır ancak bazen oyun fare bırakma tuşunu hemen tanır. artık fare işaretçisini hareket ettiremiyorum. 
>    Bunlar aynı anda meydana geldiğini düşündüğüm 2 sorun, oyunun yalnızca birkaç dakika çalışmasına neden oluyor, ardından fare çalışmıyor. 
>    Yönteminizi deneyeceğim, umarım bana geçici olarak yardımcı olur. 
>    Umarım buna radikal bir çözüm bulunur.
Thanks, problem solved. A tip from me, if you are used to using left click to attack, you can specify left hand mouse use in your mac's mouse settings and rearrange the keymap in the game, so you can continue playing with left click. .

**Comment by akifolgun** [comment]
> > Geçici bir çözüm buldum. Ekranı döndürmek için "CMD+R" tuşlarına basmanız yeterlidir; işe yarar.
> 
> Burada da aynı sorun. Sorunun nerede olduğunu biliyorum:
> 
> 1. Sorun, patlayıcı parçacık farenin sol düğme olarak ayarlanması nedeniyle ortaya çıkıyor. Dövüş sırasında oyuncuya saldırmak için sürekli olarak farenin sol tuşuna basacaktır. Bu arada ekran hareket piyasaları, sol ücret uçları her zaman ortasında ortada kaldığını belirten gelir, bu aynı sol fare uçları 2 aktif fonksiyona sahip olmak neden olur, bu çakışma Playcover'ın kırılması neden olur ve üzerine bir kez daha yazmak, bunun olacağı gelir . iki parmağınızı ekranda gösterirken olduğu gibi, bu da kamerayı hareket ettirmeden ekranın yakınlaştırılmasına ve uzaklaştırılmasına neden olur.
> 2. Saldırı bölümünde başka bir düğme ayarlamanız yeterlidir; Örneğin, saldırı genellikle E butonu olur ve fareyi bırakmadan asla fareye sol tıklamazsınız. Ancak hataların ortaya çıkmasını zorlaştıracaktır.
> 3. Geliştirici WuWa'ya vardığınızda, mobil cihazlar için ücret ve klavyeyi başlatma gibi görünüyor, böylece oyun için herhangi bir düğmeyi eşleştirmeniz veya yüklemeniz bile hala orada olduğunu ancak klavyenin kullanılabileceğini görebilirsiniz. Örneğin, karakterleri değiştirecek 1,2,3 düğmeleri, hava kancasını çalıştırmak için T düğmesi, haritayı açmak için M düğmesi... Ve fareyi serbest bırakmak için kullanılan Option veya Alt düğmesiyle benzer şekilde, ancak sorun Hem Playcover hem de Playcover'dır. WuWa bu düğmeleri kullanır, bu şekilde yapar ki ücretini bırakır için bas anında hem Wuwa hem de Playcover ücretini aynı anda bırakır, çoğu Playcover serbest kalır, ancak bazen oyun ücretini bırakma süresi hemen tanınır. artık ücret aralıklarını hareket ettiremiyorum. 
>    Bunlar aynı anda meydana geldiğinde 2 sorun var, oyunda yalnızca birkaç dakikalık çalışmaların nedeni oluyor, ardından ücret çalışmıyor. 
>    Yönteminizi deneyeceğim, umarım bana geçici olarak yardımcı olur. 
>    Umarım buna radikal bir çözüm bulunur.
Thanks, problem solved. A tip from me, if you are used to using left click to attack, you can specify left hand mouse use in your mac's mouse settings and rearrange the keymap in the game, so you can continue playing with left click. .

**Comment by Brawl345** [comment]
Same issue here, none of the solutions described here work. Neither pressing option again and wiggling the mouse nor opening the map screen nor pressing CMD+R twice to rotate the screen.

EDIT: Pressing CMD+K twice (so opening and closing keymap editor) works for me

EDIT2: Worked a few times but not consistently...

**Comment by ghdic** [comment]
In the case of Genshin Impact, clicking RMB btn solves this problem, but Wuthering Waves has not yet found a solution. The only solution is to turn the game off and on again.

**Comment by buzuosheng** [comment]
same as I. The only solution is to turn the game off and on again. And some times solved with unknown reasons

<img width="1918" alt="image" src="https://github.com/user-attachments/assets/8597e5c4-71fb-4c94-8262-30c37ff03441">

my keyboard mapping
