### ISSUE TITLE
[Game Support]: Support Minecraft Bedrock 1.21.71

### ISSUE THREAD

**Issue by mrjasonn** [PlayCover/PlayCover#1855]
### App Store link

[https://apps.apple.com/us/app/minecraft-dream-it-build-it/id479516143](https://apps.apple.com/us/app/minecraft-dream-it-build-it/id479516143)

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

It seems to open the window then just crashes instantly.
My macOS version is 15.4

### Crash log

```shell

```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [x] Yes my issue is written in English

**Comment by fazleyf** [comment]
Having the same issue as well. I would assume this may be due to encryption, since Minecraft is a paid app from the get go?

**Comment by rs9c** [comment]
You may need to turn off SIP and turn off playchain in the settings.

**Comment by SimLej18** [comment]
Having the same issue, both with nightly and stable builds, even with playchain turned off.

**Comment by jamesy0ung** [comment]
I don't have 1.21.71, but the latest version from the App Store is 1.21.81. It seems to have a duplicate library. Using PlayCover 3.10.0 on 15.5 (24F74). Minecraft works fine through the iOS subsystem if sideloaded.
```
objc[4788]: Class ProxyConfiguration is implemented in both /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/Versions/A/SafariSafeBrowsing (0x1ef3a9738) and /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/HttpClient.framework/HttpClient (0x10ed1fb50). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.
objc[4788]: Class iOSPartAInternalObject is implemented in both /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/Xal.framework/Xal (0x10e815778) and /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/xsapi-c.framework/xsapi-c (0x10e5dbfb0). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.
```

Running it without playchain also crashes,
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't add the Keychain Item.'`

**Comment by falchion10** [comment]
> I don't have 1.21.71, but the latest version from the App Store is 1.21.81. It seems to have a duplicate library. Using PlayCover 3.10.0 on 15.5 (24F74). Minecraft works fine through the iOS subsystem if sideloaded.
> 
> ```
> objc[4788]: Class ProxyConfiguration is implemented in both /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/Versions/A/SafariSafeBrowsing (0x1ef3a9738) and /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/HttpClient.framework/HttpClient (0x10ed1fb50). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.
> objc[4788]: Class iOSPartAInternalObject is implemented in both /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/Xal.framework/Xal (0x10e815778) and /Users/james/Library/Containers/io.playcover.PlayCover/Applications/com.mojang.minecraftpe.app/Frameworks/xsapi-c.framework/xsapi-c (0x10e5dbfb0). This may cause spurious casting failures and mysterious crashes. One of the duplicates must be removed or renamed.
> ```
> 
> Running it without playchain also crashes, `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't add the Keychain Item.'`

What is the iOS subsystem, and how are you sideloading it?

**Comment by TheMoonThatRises** [comment]
Explicit support for Minecraft Bedrock Edition will not be provided due to it being a paid app.

**Comment by andycode2009** [comment]
solved in https://github.com/PlayCover/PlayTools/issues/149

**Comment by andycode2009** [comment]
Download this file PlayCover.zip from 
the link: https://pan.baidu.com/s/1h8dzUqf0Kzs8sjhzlNYW-g?pwd=5j74 password: 5j74 

I am sure it works properly in macOS 15.3.1 

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/34538433-24c8-4db0-be81-62034769d5c9" />

**Comment by zjc6868668** [comment]
> You may need to turn off SIP and turn off playchain in the settings.



> You may need to turn off SIP and turn off playchain in the settings.
Hello, I would like to ask that I have turned off SIP and turned off the playchain in the play cover. But I still can't open it.
