### ISSUE TITLE
[Game Support]: Minecraft 1.21.81

### ISSUE THREAD

**Issue by falchion10** [PlayCover/PlayCover#1888]
### App Store link

https://apps.apple.com/us/app/minecraft-dream-it-build-it/id479516143

### Current issues

- [ ] Game fails to install
- [x] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

The game installs just fine, however when trying to run the game it immediately crashes. Tried disabling SIP and PlayChain and neither work. The game works just fine if you sideload it on an Apple Silicon Mac using Sideloadly, however this isn't ideal as theres no way to change resolutionDO NOT CLOSE THIS ISSUE. 

- The solution provided in this issue: https://github.com/PlayCover/PlayCover/issues/537 DOES NOT WORK. 

- Using the mcpelauncher will also not work soon because of OpenGL ES 3.1. 

- There also seems to be no solid solution in this issue: https://github.com/PlayCover/PlayTools/issues/149 and it appears to be stale.

All I would like to know is if this issue will eventually be fixed or not. A definitive yes or no would be great because this has been an issue for years at this point.

macOS Version: 15.5 (24F74)
PlayCover Version: 3.1.0 (1129)

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               minecraftpe [2606]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/minecraftpe
Identifier:            com.mojang.minecraftpe
Version:               1.21.81 (1.21.81.02)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-06-01 14:02:19.8596 -0500
OS Version:            macOS 15.5 (24F74)
Report Version:        12
Anonymous UUID:        B8886893-4B5C-84E0-979F-62BCC0B2458B


Time Awake Since Boot: 2700 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001993ca664

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [2606]

Application Specific Backtrace 0:
0   CoreFoundation                      0x0000000195242ca0 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x0000000194d06b90 objc_exception_throw + 88
2   Foundation                          0x0000000196851a78 -[NSCalendarDate initWithCoder:] + 0
3   minecraftpe                         0x000000010a54db30 _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65172448
4   minecraftpe                         0x000000010a54a0a4 _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65157460
5   minecraftpe                         0x000000010a5957a4 _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65466452
6   minecraftpe                         0x000000010a569efc _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65288108
7   minecraftpe                         0x000000010a551768 _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65187864
8   UIKitCore                           0x00000001c8f29d68 -[UINib instantiateWithOwner:options:] + 1756
9   UIKitCore                           0x00000001c99b344c -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 116
10  UIKitCore                           0x00000001c9d36320 -[UIApplication _loadMainNibFileNamed:bundle:] + 76
11  UIKitCore                           0x00000001c8d8d220 -[UIApplication _loadMainInterfaceFile] + 192
12  UIKitCore                           0x00000001c8d8c200 -[UIApplication _runWithMainScene:transitionContext:completion:] + 868
13  UIKitCore                           0x00000001c8d8bdac -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 108
14  UIKitCore                           0x00000001c8d88824 _UIScenePerformActionsWithLifecycleActionMask + 112
15  UIKitCore                           0x00000001c8d8b6a4 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 252
16  UIKitCore                           0x00000001c8d8b40c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 316
17  UIKitCore                           0x00000001c8d8a968 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 612
18  UIKitCore                           0x00000001c8d8a660 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 244
19  UIKitCore                           0x00000001c8d88e00 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 148
20  UIKitCore                           0x00000001c987fafc +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 736
21  UIKitCore                           0x00000001c9984b1c _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224
22  UIKitCore                           0x00000001c8d889ac -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 316
23  UIKitCore                           0x00000001c929bf38 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.246 + 616
24  UIKitCore                           0x00000001c8d87e44 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 208
25  UIKitCore                           0x00000001c8d87cbc -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 244
26  UIKitCore                           0x00000001c8d7d6d4 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 464
27  UIKitCore                           0x00000001c8d7d48c -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 288
28  FrontBoardServices                  0x00000001acafc1c8 __95-[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]_block_invoke + 288
29  FrontBoardServices                  0x00000001acafc6c4 -[FBSScene _callOutQueue_coalesceClientSettingsUpdates:] + 72
30  FrontBoardServices                  0x00000001acafc014 -[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:] + 504
31  FrontBoardServices                  0x00000001acb22e90 __93-[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]_block_invoke.234 + 296
32  FrontBoardServices                  0x00000001acae32a8 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 192
33  FrontBoardServices                  0x00000001acb211fc -[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:] + 516
34  libdispatch.dylib                   0x0000000194f4885c _dispatch_client_callout + 16
35  libdispatch.dylib                   0x0000000194f33b30 _dispatch_block_invoke_direct + 284
36  FrontBoardServices                  0x00000001acae31c0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
37  FrontBoardServices                  0x00000001acb3c898 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 240
38  FrontBoardServices                  0x00000001acb6a72c -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 28
39  CoreFoundation                      0x00000001951d1cd4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
40  CoreFoundation                      0x00000001951d1c68 __CFRunLoopDoSource0 + 172
41  CoreFoundation                      0x00000001951d1a38 __CFRunLoopDoSources0 + 332
42  CoreFoundation                      0x00000001951d0628 __CFRunLoopRun + 840
43  CoreFoundation                      0x00000001951cfc58 CFRunLoopRunSpecific + 572
44  HIToolbox                           0x00000001a0c6427c RunCurrentEventLoopInMode + 324
45  HIToolbox                           0x00000001a0c674e8 ReceiveNextEventCommon + 676
46  HIToolbox                           0x00000001a0df2484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
47  AppKit                              0x00000001990f7ab4 _DPSNextEvent + 684
48  AppKit                              0x0000000199a965b0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
49  AppKit                              0x00000001990eac64 -[NSApplication run] + 480
50  AppKit                              0x00000001990c135c NSApplicationMain + 880
51  AppKit                              0x000000019930dcf4 +[NSWindow _savedFrameFromString:] + 0
52  UIKitMacHelper                      0x00000001b06f4164 UINSApplicationMain + 976
53  UIKitCore                           0x00000001c8d67c9c UIApplicationMain + 148
54  minecraftpe                         0x000000010a54e5f8 _ZN7msdfgen6BitmapINS_9FloatRGBAEEclEii + 65175208
55  dyld                                0x0000000194d46b98 start + 6076


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   AppKit                        	       0x1993ca664 -[NSApplication _crashOnException:] + 256
1   AppKit                        	       0x1993ca424 -[NSApplication reportException:] + 460
2   AppKit                        	       0x19969241c NSApplicationUncaughtExceptionHandler + 152
3   CoreFoundation                	       0x1952f21d0 __handleUncaughtException + 820
4   libobjc.A.dylib               	       0x194d10dc8 _objc_terminate() + 144
5   libc++abi.dylib               	       0x19509b6b0 std::__terminate(void (*)()) + 16
6   libc++abi.dylib               	       0x19509ec48 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 88
7   libc++abi.dylib               	       0x19509ebf0 __cxa_throw + 92
8   libobjc.A.dylib               	       0x194d06cf8 objc_exception_throw + 448
9   Foundation                    	       0x196851a78 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 288
10  minecraftpe                   	       0x10a54db30 0x102884000 + 130849584
11  minecraftpe                   	       0x10a54a0a4 0x102884000 + 130834596
12  minecraftpe                   	       0x10a5957a4 0x102884000 + 131143588
13  minecraftpe                   	       0x10a569efc 0x102884000 + 130965244
14  minecraftpe                   	       0x10a551768 0x102884000 + 130865000
15  UIKitCore                     	       0x1c8f29d68 -[UINib instantiateWithOwner:options:] + 1756
16  UIKitCore                     	       0x1c99b344c -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 116
17  UIKitCore                     	       0x1c9d36320 -[UIApplication _loadMainNibFileNamed:bundle:] + 76
18  UIKitCore                     	       0x1c8d8d220 -[UIApplication _loadMainInterfaceFile] + 192
19  UIKitCore                     	       0x1c8d8c200 -[UIApplication _runWithMainScene:transitionContext:completion:] + 868
20  UIKitCore                     	       0x1c8d8bdac -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 108
21  UIKitCore                     	       0x1c8d88824 _UIScenePerformActionsWithLifecycleActionMask + 112
22  UIKitCore                     	       0x1c8d8b6a4 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 252
23  UIKitCore                     	       0x1c8d8b40c -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 316
24  UIKitCore                     	       0x1c8d8a968 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 612
25  UIKitCore                     	       0x1c8d8a660 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 244
26  UIKitCore                     	       0x1c8d88e00 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 148
27  UIKitCore                     	       0x1c987fafc +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 736
28  UIKitCore                     	       0x1c9984b1c _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224
29  UIKitCore                     	       0x1c8d889ac -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 316
30  UIKitCore                     	       0x1c929bf38 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.246 + 616
31  UIKitCore                     	       0x1c8d87e44 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 208
32  UIKitCore                     	       0x1c8d87cbc -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 244
33  UIKitCore                     	       0x1c8d7d6d4 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 464
34  UIKitCore                     	       0x1c8d7d48c -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 288
35  FrontBoardServices            	       0x1acafc1c8 __95-[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]_block_invoke + 288
36  FrontBoardServices            	       0x1acafc6c4 -[FBSScene _callOutQueue_coalesceClientSettingsUpdates:] + 72
37  FrontBoardServices            	       0x1acafc014 -[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:] + 504
38  FrontBoardServices            	       0x1acb22e90 __93-[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]_block_invoke.234 + 296
39  FrontBoardServices            	       0x1acae32a8 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 192
40  FrontBoardServices            	       0x1acb211fc -[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:] + 516
41  libdispatch.dylib             	       0x194f4885c _dispatch_client_callout + 16
42  libdispatch.dylib             	       0x194f33b30 _dispatch_block_invoke_direct + 284
43  FrontBoardServices            	       0x1acae31c0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
44  FrontBoardServices            	       0x1acb3c898 -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible] + 240
45  FrontBoardServices            	       0x1acb6a72c -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource] + 28
46  CoreFoundation                	       0x1951d1cd4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
47  CoreFoundation                	       0x1951d1c68 __CFRunLoopDoSource0 + 172
48  CoreFoundation                	       0x1951d1a38 __CFRunLoopDoSources0 + 332
49  CoreFoundation                	       0x1951d0628 __CFRunLoopRun + 840
50  CoreFoundation                	       0x1951cfc58 CFRunLoopRunSpecific + 572
51  HIToolbox                     	       0x1a0c6427c RunCurrentEventLoopInMode + 324
52  HIToolbox                     	       0x1a0c674e8 ReceiveNextEventCommon + 676
53  HIToolbox                     	       0x1a0df2484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
54  AppKit                        	       0x1990f7ab4 _DPSNextEvent + 684
55  AppKit                        	       0x199a965b0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
56  AppKit                        	       0x1990eac64 -[NSApplication run] + 480
57  AppKit                        	       0x1990c135c NSApplicationMain + 880
58  AppKit                        	       0x19930dcf4 _NSApplicationMainWithInfoDictionary + 24
59  UIKitMacHelper                	       0x1b06f4164 UINSApplicationMain + 976
60  UIKitCore                     	       0x1c8d67c9c UIApplicationMain + 148
61  minecraftpe                   	       0x10a54e5f8 0x102884000 + 130852344
62  dyld                          	       0x194d46b98 start + 6076

Thread 1:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 5:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x1950a4c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1950b73a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x1950ad764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x1950a4fa8 mach_msg + 24
4   CoreFoundation                	       0x1951d1e7c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1951d0798 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1951cfc58 CFRunLoopRunSpecific + 572
7   Foundation                    	       0x19679ec78 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x1968123a4 -[NSRunLoop(NSRunLoop) runUntilDate:] + 100
9   UIKitCore                     	       0x1c8d69070 -[UIEventFetcher threadMain] + 104
10  Foundation                    	       0x196798ba8 __NSThread__start__ + 732
11  libsystem_pthread.dylib       	       0x1950e6c0c _pthread_start + 136
12  libsystem_pthread.dylib       	       0x1950e1b80 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1950e1b6c start_wqthread + 0

Thread 8:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1950a4c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1950b73a0 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x1950ad764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x1950a4fa8 mach_msg + 24
4   CoreFoundation                	       0x1951d1e7c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1951d0798 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1951cfc58 CFRunLoopRunSpecific + 572
7   AppKit                        	       0x19921b7fc _NSEventThread + 140
8   libsystem_pthread.dylib       	       0x1950e6c0c _pthread_start + 136
9   libsystem_pthread.dylib       	       0x1950e1b80 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000132849000   x1: 0x00000001328482ec   x2: 0xffffffffffffffeb   x3: 0x000000013284aacb
    x4: 0xffffffffffffd801   x5: 0x0000000000000020   x6: 0x0000000132849000   x7: 0x0000000000001b0b
    x8: 0x0000000200cfd000   x9: 0x2046c3974a94007e  x10: 0x2046c3974a94007e  x11: 0x000000000000007f
   x12: 0x0000000000000069  x13: 0x000000013383c280  x14: 0x01000002032106e1  x15: 0x00000002032106e0
   x16: 0x0000000195120250  x17: 0x0000000204244d20  x18: 0x0000000000000000  x19: 0x0000600003b92520
   x20: 0x000060000200f180  x21: 0x0000000000000001  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000002000  x25: 0x000000000000005b  x26: 0x000000013386342f  x27: 0x00000002045ff000
   x28: 0x000000016d577108   fp: 0x000000016d576f30   lr: 0x00000001993ca65c
    sp: 0x000000016d576ef0   pc: 0x00000001993ca664 cpsr: 0x60000000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102884000 -        0x10d26ffff com.mojang.minecraftpe (1.21.81) <cb826330-f9f4-3b36-9622-6d617d410ee8> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/minecraftpe
       0x10e17c000 -        0x10e183fff com.mojang.minecraftpe.swift (1.0.0) <ba0f5871-6540-3c1e-9fcb-f22f07d0a97d> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/Frameworks/Swift.framework/Swift
       0x10e4f4000 -        0x10e653fff com.microsoft.xsapi-c (1.0) <8bd5712c-02ce-3c16-8d9d-ff7e30d69d40> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/Frameworks/xsapi-c.framework/xsapi-c
       0x10eac4000 -        0x10ecfffff com.microsoft.HttpClient (1.0) <2b4e319b-3f67-3418-a146-16fd975f91fb> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/Frameworks/HttpClient.framework/HttpClient
       0x10e734000 -        0x10e817fff com.microsoft.Xal (1.0) <93c29133-2dd3-33e2-adad-40a2f3b84698> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/Frameworks/Xal.framework/Xal
       0x10f4b4000 -        0x10f6cffff io.playcover.PlayTools (1.1.7) <7be39766-ec51-3feb-af18-fb767e9b7c37> /Users/USER/Library/Frameworks/PlayTools.framework/PlayTools
       0x10e264000 -        0x10e26ffff libobjc-trampolines.dylib (*) <d02a05cb-6440-3e7e-a02f-931734cab666> /usr/lib/libobjc-trampolines.dylib
       0x10e948000 -        0x10e94ffff io.playcover.AKInterface (1.0) <89624b2d-4a9f-3671-afc0-74c88d4cb676> /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.mojang.minecraftpe.app/PlugIns/AKInterface.bundle/Contents/MacOS/AKInterface
       0x120000000 -        0x120733fff com.apple.AGXMetalG16X (327.5) <ebf1d3ff-852c-3c06-b39e-978e8bb50313> /System/Library/Extensions/AGXMetalG16X.bundle/Contents/MacOS/AGXMetalG16X
       0x117a94000 -        0x117a9bfff com.apple.GameController.KeyboardAndMouseSupport (*) <193619c9-0cd8-3502-ba63-c1e9463e505d> /System/Library/Frameworks/GameController.framework/Versions/A/Resources/KeyboardAndMouseSupport.bundle/Contents/MacOS/KeyboardAndMouseSupport
       0x1990bd000 -        0x19a54ec7f com.apple.AppKit (6.9) <5d0da1bd-412c-3ed8-84e9-40ca62fe7b42> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x195155000 -        0x195693fff com.apple.CoreFoundation (6.9) <df489a59-b4f6-32b8-9bb4-9b832960aa52> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x194cec000 -        0x194d3f893 libobjc.A.dylib (*) <4966864d-c147-33d3-bb18-1e3979590b6d> /usr/lib/libobjc.A.dylib
       0x195086000 -        0x1950a3fff libc++abi.dylib (*) <4db4ac5c-e091-3a2e-a149-b7955b8af852> /usr/lib/libc++abi.dylib
       0x196745000 -        0x19752e2ff com.apple.Foundation (6.9) <e8f6a451-0acc-3e05-b18f-fec6618ce44a> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1c8d64000 -        0x1caaf89ff com.apple.UIKitCore (1.0) <9bac5042-7dbf-39da-8726-3fa7d5e88098> /System/iOSSupport/System/Library/PrivateFrameworks/UIKitCore.framework/Versions/A/UIKitCore
       0x1acadf000 -        0x1acbab3bf com.apple.FrontBoardServices (943.6.1) <d7443ac9-f1c1-36c9-9bed-f8c3539a7283> /System/Library/PrivateFrameworks/FrontBoardServices.framework/Versions/A/FrontBoardServices
       0x194f2d000 -        0x194f7373f libdispatch.dylib (*) <8bf83cda-8db1-3d46-94b0-d811bd77e078> /usr/lib/system/libdispatch.dylib
       0x1a0ba1000 -        0x1a0ea7fdf com.apple.HIToolbox (2.1.1) <9286e29f-fcee-31d0-acea-2842ea23bedf> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1b06f0000 -        0x1b080d0bf com.apple.UIKitMacHelper (1.0) <a5f79014-5908-30e8-8bd2-e3bceb891202> /System/Library/PrivateFrameworks/UIKitMacHelper.framework/Versions/A/UIKitMacHelper
       0x194d40000 -        0x194ddb4cf dyld (*) <9cf0401a-a938-389e-a77d-9e9608076ccf> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19511d000 -        0x195124b4f libsystem_platform.dylib (*) <519f3220-7499-334a-96d6-ccf3dc28f986> /usr/lib/system/libsystem_platform.dylib
       0x1950e0000 -        0x1950eca47 libsystem_pthread.dylib (*) <647b91fc-96d3-3bbb-af08-970df45257c8> /usr/lib/system/libsystem_pthread.dylib
       0x1950a4000 -        0x1950df653 libsystem_kernel.dylib (*) <60485b6f-67e5-38c1-aec9-efd6031ff166> /usr/lib/system/libsystem_kernel.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=1.5G written=801K(0%) resident=801K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          560K       27 
CoreAnimation                      336K       21 
CoreGraphics                        32K        2 
CoreServices                        96K        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.5G       57 
MALLOC guard page                  288K       18 
SQLite page cache                  256K        2 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                        192K       10 
__AUTH                            5848K      693 
__AUTH_CONST                      77.5M      922 
__CTF                               824        1 
__DATA                            26.5M      911 
__DATA_CONST                      34.5M      935 
__DATA_DIRTY                      2710K      328 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       629.8M       11 
__OBJC_RO                         61.4M        1 
__OBJC_RW                         2396K        1 
__TEXT                             1.0G      952 
__TEXT (graphics)                 7408K        2 
__TEXT (network)                 175.2M        6 
__TPRO_CONST                       128K        2 
mapped file                      230.8M       27 
page table in kernel               801K        1 
shared memory                     1376K       14 
===========                     =======  ======= 
TOTAL                              3.8G     4968
```

### What version of PlayCover are you using?

Nightly/beta (please specify build number)

### What version of macOS are you using?

Other (please specify)

### Issue Language

- [x] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
Direct support for Minecraft will not be provided due to it being a paid app.

**Comment by falchion10** [comment]
How is that even an issue? You can literally decrypt the app yourself on a jailbroken device and use your own IPA. That is not piracy. Providing 0 support for any paid app is the wrong way to go about it.

**Comment by falchion10** [comment]
As an FYI to anyone apart of the team, downloading free apps in the form of an ipa is also piracy because it violate's the app's license. It makes 0 sense to not support paid apps. Unless you are manually decrypting the ipa on a device it is piracy. It does not matter if the app is free or paid. That should not be where the line is drawn in this discussion.

**Comment by andycode2009** [comment]
solved in https://github.com/PlayCover/PlayTools/issues/149

**Comment by andycode2009** [comment]
Download this file PlayCover.zip from 
the link: https://pan.baidu.com/s/1h8dzUqf0Kzs8sjhzlNYW-g?pwd=5j74 password: 5j74 

I am sure it works properly in macOS 15.3.1 

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/34538433-24c8-4db0-be81-62034769d5c9" />

**Comment by falchion10** [comment]
This issue isn't solved until these changes are merged into the main branch. Also literally can't even download it without creating an account.

**Comment by andycode2009** [comment]
sorry I'm used to use this netdisk
here is the google drive
https://drive.google.com/file/d/1dcipx94rzzJr8cDfByDRrJcJsMm_kbwn/view?usp=sharing
I think it is hard to make these changes are merged into the main branch.
and we all know why

**Comment by falchion10** [comment]
> sorry I'm used to use this netdisk here is the google drive https://drive.google.com/file/d/1dcipx94rzzJr8cDfByDRrJcJsMm_kbwn/view?usp=sharing I think it is hard to make these changes are merged into the main branch. and we all know why

Did you build this version of PlayCover what that version of PlayTools mentioned in the issue? If so is there anyway I can contact you via Discord so you could show me the build process for PlayTools and PlayCover?

**Comment by andycode2009** [comment]
in fact, I just build PlayTools.framework and replace /Applications/PlayCover.app/Contents/Frameworks/PlayTools.framework

the commit a6646cc  (playtools)
 is 3.0.0 version because when I build it there is no 3.1.0 version

but it works well too with the 3.1.0 playcover.app

to build it 
clone the playtools
replace PlayTools/MysticRunes/
-PlayedApple.swift
-PlayedAppleConstants.swift
-PlayedAppleDB.swift
from https://github.com/Ryu-ga/PlayTools/commit/a6646cc600a3dba58c97d6b86380b1750d2ef674

install SwiftLint.pkg

follow the "How to Build" section
https://github.com/Ryu-ga/PlayTools?tab=readme-ov-file#how-to-build
