### ISSUE TITLE
V1.1.1 problem Intermittently uncontrollable when running Genshin Impact

### ISSUE THREAD

**Issue by sheaahhoi1** [PlayCover/PlayCover#28]
1.0.6 version problem Intermittently uncontrollable when running Genshin Impact
The more frequently a key (keyboard) is pressed, the more likely it becomes inoperable.

**Comment by lixin9311** [comment]
I experience the same problem while playing BA.
A workaround is, while playing the game if you found it does not respond to your touches, go to Preference, and toggle this option on and off.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/371475/178906769-1a028f7c-4770-4421-9b34-7b4bc5150b83.png">

Meanwhile I will try to look into this issue.

**Comment by JoseMoreville** [comment]
You can also try using two keys to kinda fix the problem, but its just a workaround you need to do everytime you stop moving

**Comment by sheaahhoi1** [comment]
@JoseMoreville Can't be used, can be easily killed in Spiral Abyss

**Comment by sheaahhoi1** [comment]
V1.0.7problem persists

**Comment by XuYicong** [comment]
Encountered a similar problem in 1.0.5 when fighting in the Abyss, after upgrading from 1.0.0. Some keys lagged and more lost.

**Comment by sheaahhoi1** [comment]
> That might be a shot in the dark but I had a similar issue where the keyboard randomly stopped responding (mouse still did work) and found out it was actually caused by the Terminal (I always leave it open).
> 
> After unchecking "Secure Keyboard Entry" in the Terminal app, I never had this issue again.

@kamui545 This method is not directly related and cannot be solved

**Comment by XuYicong** [comment]
Is it possible to move macro record event invocation to a lower priority dispatch queue, so that it does not take up too much resource for fake touch? I mean the `touchcam()` in `Toucher.swift` in playTools.

**Comment by RigoLigoRLC** [comment]
This problem occurred to me after I changing Genshin's framerate to 60 fps. My computer is a MacBook Air M1. PlayCover version 1.0.7. After the keys freezes I'll have to switch window with Cmd+Tab and it may be responsive again. Happens frequently and severely affects combats.

**Comment by RigoLigoRLC** [comment]
Okay just in the meantime it froze for more than 5 times. I had to change it back to 30 fps. Hope this issue is addressed soon.

**Comment by endsha** [comment]
This problem still persists in v1.1.1. I'm using Macbook Pro M1 Pro 16 inch with 32GB RAM, when I change from 60hz to 120hz (the game runs smoothly without any fps drop), the game is sometimes uncontrollable. I have to switch window with Cmd+Tab multiple times, have to switch back to 60hz to play :( . Hope this will be fixed as soon as posible.

**Comment by JoseMoreville** [comment]
Please, keep 60fps until we find a way to fix it. Thanks.

**Comment by XuYicong** [comment]
Please try with the latest nightly. Although your description of the issue is unclear, the latest nightly has hopefully fixed lots of keymapping issues.

**Comment by sheaahhoi1** [comment]
@XuYicong latest nightly. Is it an unreleased version?
How do I download it?

**Comment by ZhichGaming** [comment]
https://nightly.link/PlayCover/PlayCover/actions/runs/3055580312/PlayCover_nightly_66.dmg.zip

**Comment by sheaahhoi1** [comment]
@XuYicong @ZhichGaming In the latest nightly version, the keyboard mapping and keyboard operation are improved, but the mouse rotation is delayed, the archer is difficult to shoot, and the frame rate seems to drop, but it is smooth

**Comment by IsaacMarovitz** [comment]
@sheaahhoi1 Please try nightly 85, there have been further performance improvements. In terms of bow user precision, it is difficult to improve that further.

**Comment by sheaahhoi1** [comment]
@IsaacMarovitz nightly 85 This version cannot use the mouse to rotate the screen for 3~4 seconds when the mouse "option key" is switched to the application
The nightly version has a common input delay, which will cause no input response in some battle scenes

**Comment by IsaacMarovitz** [comment]
Please open that in a new issue.
